name: dog_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #core packages
  flutter_bloc: ^8.1.3
  easy_localization: ^3.0.3
  dio: ^5.4.0
  flutter_native_splash: ^2.3.8
  equatable: ^2.0.5
  go_router: ^12.1.3
  collection: ^1.18.0 
  
  #ui
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  sliding_up_panel: ^2.0.0+1

  #internal packages
  core:
    path: ./packages/core/
  models:
    path: ./packages/models/
  dog_repository:
    path: ./packages/dog_repository/
  dependency_injection:
    path: ./packages/dependency_injection/
  


dev_dependencies:
  build_runner: ^2.4.7
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/translations/
  fonts:
    - family: GalanoGrotesque
      fonts:
        - asset: assets/fonts/GalanoGrotesqueSemiBold.otf
          weight: 600
        - asset: assets/fonts/GalanoGrotesqueMedium.otf
          weight: 500
        - asset: assets/fonts/GalanoGrotesqueRegular.otf
          weight: 400

