name: dog_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #core packages
  flutter_bloc: ^8.1.3
  easy_localization: ^3.0.3
  dio: ^5.4.0
  flutter_native_splash: ^2.3.8
  equatable: ^2.0.5
  go_router: ^12.1.3
  collection: ^1.18.0 
  flutter_screenutil: ^5.9.0

  #internal packages
  core:
    path: ./packages/core/
  models:
    path: ./packages/models/
  dog_repository:
    path: ./packages/dog_repository/
  dependency_injection:
    path: ./packages/dependency_injection/

  #ui
  cupertino_icons: ^1.0.2
  meta: ^1.10.0

dev_dependencies:
  build_runner: ^2.4.7
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  

flutter:
  uses-material-design: true
